server:
  port: 80
  servlet:
    context-path: /api
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8080/eureka
spring:
  application:
    name: gateway
  datasource:
    url: jdbc:mysql://localhost:3306/test
  cloud:
    gateway:
      discovery:
        locator:
          # 是否和服务注册与发现组件结合，设置为 true 后可以直接使用应用名称调用服务
          enabled: true
      routes:
        - id: hello_gateway
          uri: http://localhost:8082/admin
          predicates:
            - path=/
mybatis:
  config-location:
