server:
  port: 8085
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8080/eureka

spring:
  application:
    name: gateway
  datasource:
    url: jdbc:mysql://localhost:3306/test
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    gateway:
      discovery:
          locator:
            enabled: true
      routes:
      - id: hello_gateway
        uri: http://localhost:8082
        predicates:
        - Path=/admin/** #把进行网关的，所有admin开头的请求都转向http://localhost:8082服务（把Ip和端口替换为Uri定义的，其余不变）
