server:
  port: 8080
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: false #false 表示自己是注册中心，我的职责是维护服务实例，并不需要去检索服务
    register-with-eureka: false # 表示自己不需要向自己注册自己，自己就是注册中心
    serviceUrl:
      #设置与 Eureka Server 交互的地址查询服务和注册服务都需要依赖这个地址
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/ #单机版
      #defaultZone: http://eurekademo01.com:7001/eureka/,http://eurekademo02.com:7002/eureka/ #单机版
spring:
  application:
    name: eureka
