server:
  port: 8083
  servlet:
    context-path: /crawler
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8080/eureka
spring:
  application:
    name: crawler
  datasource:
    url: jdbc:mysql://localhost:3306/test
mybatis:
  config-location:
feign:
  client:
    config:
      default:
        connectTimeout: 1000 #Feign的连接建立超时时间，默认为10秒
        readTimeout: 10000 #Feign的请求处理超时时间，默认为60秒