server:
  port: 8083
  servlet:
    context-path: /crawler
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8080/eureka
spring:
  application:
    name: crawler
  datasource:
    url: jdbc:mysql://localhost:3306/test
mybatis:
  config-location: